### PR TITLE
nsqd: fix ephemeral channel sub live lock

### LINKED ISSUE #1251: nsqd: ephemeral topic/channel churn can live-lock
from https://github.com/nsqio/nsq/pull/1246

If consumers of ephemeral topics and channels come and go fast enough, for a short period of time, some can get stuck in indefinite retry loops.

Demo by @slayercat:

```go
package main

import nsq "github.com/nsqio/go-nsq"
import "time"
import "log"
import "fmt"

func nsqSubscribe(addr string, topic string, channel string, hdlr nsq.HandlerFunc) error {
	consumer, err := nsq.NewConsumer(topic, channel, nsq.NewConfig())
	if err != nil {
		print("new consumer error: ", err, "\n")
		time.Sleep(1 * time.Second) //wait 1s
		panic(err)
	}
	consumer.AddHandler(hdlr)
	for {
		err = consumer.ConnectToNSQD(addr)
		if err != nil {
			log.Printf("connect nsqd error: %v. retry\n", err)
			time.Sleep(1 * time.Second) //wait 1s
			continue
		} else {
			break
		}
	}
	_ = <-consumer.StopChan
	panic("nsq conn dead topic=" + topic + " channel=" + channel)
	return nil
}

func handlerFunc1(message *nsq.Message) error {
	message.Finish()
	return nil
}

func main() {
	for i := 0; i < 10; i++ {
		go nsqSubscribe("127.0.0.1:4150",
			fmt.Sprintf("testTopic%d#ephemeral", i),
			fmt.Sprintf("testChannel%d#ephemeral", i),
			handlerFunc1)
	}

	nsqSubscribe("127.0.0.1:4150", ("testTopic#ephemeral"), ("testChannel#ephemeral"), handlerFunc1)
}
```

Start a simple stand-alone `nsqd`, and then build and run the demo above in a bash loop:

```sh
go build -o demo demo.go

for I in $(seq 100); do
    ./demo &
    sleep 0.1
    kill $!
done
```

Then, nsqd will get stuck in the client topic/channel subscribe retry loop, seemingly indefinitely (long after the above loop finishes, and even after nsqd is signalled to exit gracefully):

```
[nsqd] 2020/05/09 13:13:17.694506 INFO: CHANNEL(testChannel6#ephemeral): deleting
[nsqd] 2020/05/09 13:13:17.694701 INFO: TOPIC(testTopic6#ephemeral): new channel(testChannel6#ephemeral)
[nsqd] 2020/05/09 13:13:17.694786 INFO: TOPIC(testTopic6#ephemeral): deleting channel testChannel6#ephemeral
[nsqd] 2020/05/09 13:13:17.694796 INFO: CHANNEL(testChannel6#ephemeral): deleting
[nsqd] 2020/05/09 13:13:17.695104 INFO: TOPIC(testTopic6#ephemeral): new channel(testChannel6#ephemeral)
[nsqd] 2020/05/09 13:13:17.695187 INFO: TOPIC(testTopic6#ephemeral): deleting channel testChannel6#ephemeral
[nsqd] 2020/05/09 13:13:17.695203 INFO: CHANNEL(testChannel6#ephemeral): deleting
[nsqd] 2020/05/09 13:13:17.695535 INFO: TOPIC(testTopic6#ephemeral): new channel(testChannel6#ephemeral)
[nsqd] 2020/05/09 13:13:17.695620 INFO: TOPIC(testTopic6#ephemeral): deleting channel testChannel6#ephemeral
[nsqd] 2020/05/09 13:13:17.695631 INFO: CHANNEL(testChannel6#ephemeral): deleting
[nsqd] 2020/05/09 13:13:17.696009 INFO: TOPIC(testTopic6#ephemeral): new channel(testChannel6#ephemeral)
[nsqd] 2020/05/09 13:13:17.696102 INFO: TOPIC(testTopic6#ephemeral): deleting channel testChannel6#ephemeral
[nsqd] 2020/05/09 13:13:17.696115 INFO: CHANNEL(testChannel6#ephemeral): deleting
[nsqd] 2020/05/09 13:13:17.696359 INFO: TOPIC(testTopic6#ephemeral): new channel(testChannel6#ephemeral)
```

Some ideas:
  * add 100ms of sleep before retry
  * add random sleep between 1ms and 250ms between retries
  * give up after 2 retries

### PR DESCRIPTION
**Pull request by mreiferson**
Fixes #1251 

I noticed a few things while debugging this...

The reproducible steps from #1251 caused file descriptor exhaustion in `nsqd` on my macOS laptop (default configuration) The stacktrace from `nsqd` confirmed what had previously been reported, a ton of contention on `nsqd.RWMutex`, but I noticed this in particular:

```goroutine 1830 [runnable]:
syscall.syscall(0x10b9ea0, 0xb, 0x33, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/sys_darwin.go:63 +0x2e
syscall.fcntl(0xb, 0x33, 0x0, 0xc001697c38, 0x10d7df7, 0xc00017b620)
	/usr/local/Cellar/go/1.15.2/libexec/src/syscall/zsyscall_darwin_amd64.go:338 +0x58
internal/poll.(*FD).Fsync(0xc00017b620, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/internal/poll/fd_fsync_darwin.go:18 +0xa8
os.(*File).Sync(0xc000318570, 0xc00060fb00, 0x25)
	/usr/local/Cellar/go/1.15.2/libexec/src/os/file_posix.go:158 +0x4c
github.com/nsqio/nsq/nsqd.writeSyncFile(0xc001281060, 0x20, 0xc00060fb00, 0x25, 0x30, 0xc001281060, 0x20)
	/Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/nsqd.go:322 +0xff
github.com/nsqio/nsq/nsqd.(*NSQD).PersistMetadata(0xc0001b6000, 0xc001b43f18, 0x2)
	/Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/nsqd.go:415 +0xb2b
github.com/nsqio/nsq/nsqd.(*NSQD).Notify.func1()
	/Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/nsqd.go:575 +0x133
github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap.func1(0xc000f843c0, 0xc0001b6100)
	/Users/mreiferson/dev/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:14 +0x27
created by github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap
	/Users/mreiferson/dev/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:13 +0x65
```

This was the goroutine ultimately holding the lock. We don't need to be persisting metadata for ephemeral topics/channels, so after changing that it "fixed" the issue in my testing. It would still be possible to construct a pathological test to cause this, so I additionally limited the retry loop and increased the timeout (which, IMO, is the "correct" behavior here anyway).

I fixed a few other things while debugging...

### CODE REVIEW

File: nsqd/topic.go [hunk 1]
```diff
@@ -145,23 +145,29 @@ func (t *Topic) GetExistingChannel(channelName string) (*Channel, error) {
...
 	if !ok {
-		t.Unlock()
+		t.RUnlock()
 		return errors.New("channel does not exist")
 	}
-	delete(t.channelMap, channelName)
-	// not defered so that we can continue while the channel async closes
-	numChannels := len(t.channelMap)
-	t.Unlock()
+	t.RUnlock()
```
Comment (ploxiln) [inline nsqd/topic.go:154]: looks like you can `RUnlock` in just one place, just before `if !ok {`

File: nsqd/topic.go [hunk 2]
```diff
@@ -145,23 +145,29 @@ func (t *Topic) GetExistingChannel(channelName string) (*Channel, error) {
...
 
 	t.nsqd.logf(LOG_INFO, "TOPIC(%s): deleting channel %s", t.name, channel.name)
 
 	// delete empties the channel before closing
 	// (so that we dont leave any messages around)
+	//
+	// we do this before removing the channel from map below (with no lock)
+	// so that any incoming subs will error and not create a new channel
```
Comment (ploxiln) [inline nsqd/topic.go:162]: it seems like, for normal non-ephemeral channels, there are no checks if the channel is exiting, in either `Channel.AddClient()` or `ProtocolV2.SUB()`

Comment (mreiferson) [reply nsqd/topic.go:161]: Fixed this in https://github.com/nsqio/nsq/pull/1314/commits/aadef464b04b173bb9af02051e836982ceec0369 PTAL

**Comment by mreiferson** [comment]
@ploxiln review this if you're reviewing things 😏

File: nsqd/protocol_v2.go [hunk 3]
```diff
@@ -615,19 +615,20 @@ func (p *protocolV2) SUB(client *clientV2, params [][]byte) ([]byte, error) {
...
-				fmt.Sprintf("channel consumers for %s:%s exceeds limit of %d",
-					topicName, channelName, p.nsqd.getOpts().MaxChannelConsumers))
+			return nil, protocol.NewFatalClientErr(err, "E_SUB_FAILED", "SUB failed "+err.Error())
 		}
 
 		if (channel.ephemeral && channel.Exiting()) || (topic.ephemeral && topic.Exiting()) {
 			channel.RemoveClient(client.ID)
-			time.Sleep(1 * time.Millisecond)
-			continue
+			if i < 2 {
```
Comment (ploxiln) [inline nsqd/protocol_v2.go:627]: only two attempts ... could do a couple more to be "safe" ... but ephemeral channel clients can retry too, and already give up guarantees. ok, makes sense

**Review by ploxiln — APPROVED** [review]

File: nsqd/protocol_v2.go [hunk 4]
```diff
@@ -615,19 +615,20 @@ func (p *protocolV2) SUB(client *clientV2, params [][]byte) ([]byte, error) {
...
 	var channel *Channel
-	for {
+	for i := 1; ; i++ {
 		topic := p.nsqd.GetTopic(topicName)
 		channel = topic.GetChannel(channelName)
 		if err := channel.AddClient(client.ID, client); err != nil {
-			return nil, protocol.NewFatalClientErr(nil, "E_TOO_MANY_CHANNEL_CONSUMERS",
-				fmt.Sprintf("channel consumers for %s:%s exceeds limit of %d",
-					topicName, channelName, p.nsqd.getOpts().MaxChannelConsumers))
+			return nil, protocol.NewFatalClientErr(err, "E_SUB_FAILED", "SUB failed "+err.Error())
```
Comment (ploxiln) [inline nsqd/protocol_v2.go:622]: hmm, now this is where the exiting will be checked, and we won't retry for ephemeral channels exiting, as intended

Comment (mreiferson) [reply nsqd/protocol_v2.go:622]: I think that's fine, if we looked up a channel that is indeed exiting we _want_ this to fail here.

**Comment by mreiferson** [comment]
@jehiah last chance before I land this 😏

**Review by jehiah — APPROVED** [review]
👍  I've not reviewed exhaustively, but this LGTM
