### PR TITLE
nsqd: fix deflate level handling

### LINKED ISSUE #926: deflate level specified from client lib in IDENTIFY not work
Greetings,
Upon identify with specified deflate level, nsqd does not accept it but using max deflate level in option.

in IDENTIFY(), identifyData.Deflate does not used to decide the deflate level, is it a bug here?
line #396, protocol_v2.go
`deflate := p.ctx.nsqd.getOpts().DeflateEnabled && identifyData.Deflate
	deflateLevel := 0
	if deflate {
		if identifyData.DeflateLevel <= 0 {
			deflateLevel = 6
		}
		deflateLevel = int(math.Min(float64(deflateLevel), float64(p.ctx.nsqd.getOpts().MaxDeflateLevel)))
	}`

besides, there is a typo in attribute of client connection in nsqadmin, when deflate apply.
image

### PR DESCRIPTION
**Pull request by jehiah**
This fixes #926 by properly using the client provided deflate level from identify

### CODE REVIEW

**Comment by ploxiln** [comment]
Can you add the deflate level to the log message "upgrading connection to deflate" below?

**Comment by jehiah** [comment]
@ploxiln good idea. PTAL

File: nsqd/protocol_v2.go [hunk 1]
```diff
@@ -399,7 +399,7 @@ func (p *protocolV2) IDENTIFY(client *clientV2, params [][]byte) ([]byte, error)
 		if identifyData.DeflateLevel <= 0 {
 			deflateLevel = 6
```
Comment (ploxiln) [inline nsqd/protocol_v2.go]: one more small thing - setting `deflateLevel` here has no effect, I think we want to set `identifyData.DeflateLevel` to the default of 6 here

Comment (mreiferson) [inline nsqd/protocol_v2.go]: Instead of that, we should drop the change on line 402 and update line 398 to:

```go
deflateLevel := identifyData.DeflateLevel
```

Otherwise the JSON response below would be broken.

**Comment by mreiferson** [comment]
Want to fix the typo reported in #926 while you're in here??!?!?!
